name: Sample Workflow

on:
  push:
    branches: [ main526 ] # it is just for testing purpose

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@main  # This should trigger an unpinned action warning
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
      
    - name: Deploy
      run: |
        echo "Deploying to production..."
        echo "SECRET_KEY=sk_test_1234567890abcdef"  # This should trigger a hardcoded secret warning
        echo "API_TOKEN=ghp_abcdef1234567890"       # This should trigger a hardcoded secret warning
        echo "Deploying with token: ${{ secrets.DEPLOY_TOKEN }}"  # This should trigger an exposed secret reference warning
